metadata:
    name: apk-automation
    format: "Lava-Test-Shell Test Definition 1.0"
    description: "Automate testing with Android APK."
    maintainer:
        - seoji@nexell.co.kr
    os:
        - android
    devices:
        - hi6220-hikey
        - s5p4418-navi-ref
        - s5p4418-navi-ref-qt
        - s5p4418-navi-ref-tiny
    scope:
        - performance

params:
    SKIP_INSTALL: "false"
    BOOT_TIMEOUT: "300"
    ANDROID_SERIAL: ""
    TEST_NAME: "antutu-nexell"
    LOOPS: "13"
    APK_DIR: "./apks"
    BASE_URL: "http://confluence.nexell.co.kr:8080/test/android/apk/"
    ARTIFACTORIAL_URL: "http://192.168.1.20:9090/artifacts/team/nx-solution-team2/"
    ARTIFACTORIAL_TOKEN: "e2e701c507849e1dfb243286d4e5dc5e"

run:
    steps:
        - echo "test1:" "pass"
        # display stay awake
        #- adb shell settings put global stay_on_while_plugged_in 3
        # swipe screen
        #- adb shell input swipe 817 500 817 300
        - cd ./automated/android/apk-automation
        - ./apk-automation.sh -S "${SKIP_INSTALL}" -t "${BOOT_TIMEOUT}" -s "${ANDROID_SERIAL}" -n "${TEST_NAME}" -l "${LOOPS}" -d "${APK_DIR}" -u "${BASE_URL}"
        # Upload test output to artifactorial.
        - cp "./output/${TEST_NAME}/result.txt" "./output/result.txt"
        - tar caf "output-${TEST_NAME}.tar.xz" "./output"
        - ../../utils/upload-to-artifactorial.sh -a "output-${TEST_NAME}.tar.xz" -u "${ARTIFACTORIAL_URL}" -t "${ARTIFACTORIAL_TOKEN}"
        # Send test result to LAVA.
        - ../../utils/send-to-lava.sh "./output/result.txt"
